# Generated by Django 3.2.16 on 2022-11-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20221105_0224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatrixPic',
        ),
    ]
